#Deployment Pods kubernets
#pod postgres
- name: deployment postgres
  become: yes
  community.kubernetes.k8s:
    state: present
    remote_src: /home/{{ansible_user}}/Documents/django/deploy-django

- name: deployment app
  become: yes
  shell: kubectl apply -f /home/{{ansible_user}}/Documents/django/deploy-django