#Deployment Pods kubernets
#pod postgres
- name: deployment postgres
  community.kubernetes.k8s:
    state: present
    src: /home/boomer/Documents/postgres/

- name: deployment app
  community.kubernetes.k8s:
    state: present
    src: /home/boomer/Documents/deploy-django/