#Deployment Pods kubernets
#pod postgres
- name: deployment postgres
  become: yes
  shell: kubectl apply -f /home/{{ansible_user}}/Documents/django/postgres

#pod app
- name: deployment app
  become: yes
  shell: kubectl apply -f /home/{{ansible_user}}/Documents/django/deploy-django