#Deployment Pods kubernets
#pod postgres
- name: deployment postgres
  become: yes
  community.kubernetes.k8s:
    state: present
    src: /home/{{ansible_user}}/Documents/postgres/

- name: deployment app
  become: yes
  community.kubernetes.k8s:
    state: present
    src: /home/{{ansible_user}}/Documents/deploy-django/