# Minikube
- name: Download Minikube
  become: yes
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /home/vagrant/minikube-linux-amd64
    mode: 0440