# Minikube
- name: Download Minikube
  become: yes
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /home/vagrant/minikube-linux-amd64
    mode: 0440

- name: Install Minikube
  become: yes
  shell: "install minikube-linux-amd64 /usr/local/bin/minikube"
  args: 
    chdir: /home/vagrant
  register: install_minikube

- name: Debug install_minikube
  become: yes
  debug: 
    var: install_minikube

#- name: Start Minikube
#  become: yes
#  shell: minikube start


- name: copy minikube conf
  become: yes
  copy:
    src: /root/.minikube
    dest: /home/vagrant/
    remote_src: yes
    owner: vagrant
    group: vagrant