version: '3.7'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - /Users/yurkin-rv/Documents/project/django-project/docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - jenkins
    jenkins:
        image: jenkinsci/blueocean
        environment:
          DOCKER_HOST: tcp://docker:2376
          DOCKER_CERT_PATH: /certs/client
          DOCKER_TLS_VERIFY: 1
        volumes:
            #- /var/run/docker.sock:/var/run/docker.sock
            #- /var/jenkins_home:/var/jenkins_home
            - jenkins_data:/var/jenkins_home
            - docker-certs:/certs/client:ro
        depends_on:
            - docker

    docker:
      image: docker:dind
      privileged: true
      environment:
          DOCKER_TLS_CERTDIR: /certs
      volumes:
            - jenkins_data:/var/jenkins_home
            - docker-certs:/certs/client
            - docker-data:/var/lib/docker
volumes:
    jenkins_data:
    docker-certs:
    docker-data: