#Login and Start
- name: Start docker on boot
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Log into DockerHub
  become: yes
  docker_login:
    username: boomer9955
    password: bmw1258963-

#pull image
- name: Pull an image
  become: yes
  community.docker.docker_image:
    name: boomer9955/mydjango
    source: pull

#minikube
- name: Check Minikube's status.
  command: minikube status
  register: minikube_status
  changed_when: false
  ignore_errors: true
#Otherwise will start minikube
- name: Start Minikube if it's not running.
  command: minikube start
  when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

#start container
- name: start application
  command: kubectl run djangoweb --image=boomer9955/mydjango deployment "djangoweb" created
  register: command_result
- debug:
    var: command_result.stdout_lines