#Login and Start
- name: Start docker on boot
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Log into DockerHub
  docker_login:
    username: boomer9955
    password: bmw1258963-

#pull image
- name: Pull an image
  community.docker.docker_image:
    name: boomer9955/mydjango
    source: pull

#start image
- name: start minikube
  docker_container:
    name: gcr.io/k8s-minikube/kicbase
    state: started