#Login and Start
- name: Start docker on boot
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Log into DockerHub
  become: yes
  docker_login:
    username: boomer9955
    password: bmw1258963-

#pull image
- name: Pull an image
  become: yes
  community.docker.docker_image:
    name: boomer9955/mydjango
    source: pull

#minikube
- name: minikube
  shell: "minikube status"
  register: shell_result
- debug:
    msg: "Запуск minikube.."
    when: shell_result.stdout_lines.find("Stopped") == start
- name: start
  shell: "minikube start"
  register: shell_result