# autorize
- name: autorize
  become: yes
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# install app
- name: apt-get upgrade
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

#iptables
- name: install iptables
  become: yes
  apt:
    name: iptables
    state: present
    update_cache: yes

- name: set bridge-nf-call-iptables = 1
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: net.bridge.bridge-nf-call-iptables = 1
    
#Python
- name: Package Python
  apt:
    force_apt_get: yes
    name: ['python3-pip', 'python3-setuptools', 'python3-virtualenv', 'python3-pymongo', 'python3-selinux', 'docker-compose', 'net-tools']
    install_recommends: yes
    state: present
  become: yes
  tags:
    - mongo

#System config
- name: Install SELinux
  become: yes
  apt:
    name: ['selinux-basics', 'selinux-policy-default', 'auditd']

- name: disable swap
  become: yes
  shell: /usr/sbin/swapoff -a

- name: disable swap permanently
  become: yes
  lineinfile:
    path: /etc/fstab
    regexp: '^[^#].*swap.*$'
    state: absent

- name: delete swapfile
  become: yes
  file:
    path: /swapfile
    state: absent

- name: create /vagrant directory
  become: yes
  file:
    path: /vagrant
    state: directory