apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoweb
  labels:
    app: djangoweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoweb
  template:
    metadata:
      labels:
        app: djangoweb
    spec:
      containers:
        - name: djangoweb
          image: boomer9955/mydjango:latest
          ports:
            - containerPort: 8010