apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoweb
  labels:
    app: djangoweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: djangoweb
    spec:
      containers:
        - name: djangoweb
          image: dockerbogo/django-minikube:1.0.0
          ports:
            - containerPort: 8010