# apt
- name: apt-get upgrade
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

# Kubectl
- name: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  become: yes
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add a line to a file if it does not exist, without passing regexp
  become: yes
  lineinfile:
    create: yes
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

- name: apt-get update
  become: yes
  apt: 
    update_cache: yes

- name: Install packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kubectl
#kubeadm
- name: Install kubeadm
  become: yes
  apt:
    name: kubeadm
    state: present
    update_cache: yes
#kubelet
- name: Install kubelet
  become: yes
  apt:
    name: kubelet
    state: present
    update_cache: yes

- name: start and enable kubelet service
  become: yes
  service:
    name: kubelet
    enabled: yes
    state: started

- name: enable kubectl autocompletion
  become: yes
  lineinfile:
    path: /home/vagrant/.bashrc
    line: source <(kubectl completion bash)
    insertafter: EOF

- name: enable kubectl alias
  become: yes
  lineinfile:
    path: /home/vagrant/.bashrc
    line: alias k="kubectl"
    insertafter: EOF

- name: enable kubectl alias
  become: yes
  lineinfile:
    path: /home/vagrant/.bashrc
    line: alias kc="kubectl"
    insertafter: EOF