- name: install dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: add gpg key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: verify
  become: yes
  apt_key:
    id: 0EBFCD88
    state: present

- name: set up the repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
    filename: docker
    update_cache: yes

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot

- name: Install python
  become: yes
  apt:
    name: ['python3-pip', 'python3-setuptools', 'virtualenv']
    update_cache: yes
  notify: good install python

- name: Install docker-compose
  become: yes
  pip:
    name: docker-compose
  notify: good install docker-compose

- name: Install minikube
  become: yes
  apt:
    name: minikube
    state: present
    update_cache: yes
  notify: good install minikube