- name: install dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: add gpg key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: verify
  become: yes
  apt_key:
    id: 0EBFCD88
    state: present

- name: set up the repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
    filename: docker
    update_cache: yes

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot

- name: Install python
  become: yes
  apt:
    name: ['python3-pip', 'python3-setuptools', 'virtualenv']
    update_cache: yes
  notify: good install python

- name: Install docker-compose
  become: yes
  pip:
    name: docker-compose
  notify: good install docker-compose

# VirtualBox
- name: apt-get upgrade
  become: yes
  apt:
    #upgrade: yes
    update_cache: yes

- name: Install VirtualBox
  become: yes
  apt:
    name: virtualbox
    update_cache: yes
  notify: good install python

# Kubectl
- name: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  become: yes
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add a line to a file if it does not exist, without passing regexp
  become: yes
  lineinfile:
    create: yes
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

- name: apt-get update
  become: yes
  apt: 
    update_cache: yes

- name: Install packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kubectl

# Minikube
- name: Download Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /home/boomer/Downloads/minikube-linux-amd64
    mode: 0440

- name: Install Minikube
  become: yes
  shell: "install minikube-linux-amd64 /usr/local/bin/minikube"
  args: 
    chdir: /home/boomer/Downloads
  register: install_minikube

- name: Debug install_minikube
  debug: 
    var: install_minikube

- name: Start minikube
  shell: "minikube start"
  register: start_minikube