#docker_python_docker-compose
- name: install dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: add gpg key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: verify
  become: yes
  apt_key:
    id: 0EBFCD88
    state: present

- name: set up the repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
    filename: docker
    update_cache: yes

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes

#docker group and login
- name: Add vagrant user to docker group
  become: yes
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Log into DockerHub
  become: yes
  docker_login:
    username: boomer9955
    password: bmw1258963-

#pull image
- name: Pull an image
  become: yes
  shell: docker pull boomer9955/mydjango:latest