all:
    children:
        myserver:
            hosts:
                server:
                    host_key_checking: False
                    ansible_connection: ssh
                    ansible_user: boomer
                    ansible_host: 192.168.31.126
                    ansible_port: 22