pipeline { 
    agent any 
    stages {
        stage('Cloning our Git') { 
            steps { 
                checkout scm
            }
        }
        stage('Building our image') { 
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'myserver01', keyFileVariable: '', passphraseVariable: '', usernameVariable: 'boomer')]) {
                    ansiblePlaybook inventory: 'ansible/hosts.yml', playbook: 'ansible/ansible_script.yml', credentialsId: {myserver01}
                }                  
            }
        }
    }
}
