pipeline { 
    agent any 
    stages {
        stage('Cloning our Git') { 
            steps { 
                checkout scm
            }
        }
        stage('install app') { 
            steps {
                ansiblePlaybook credentialsId: 'myserver01', disableHostKeyChecking: true, inventory: 'ansible/hosts.yml', playbook: 'ansible/deploymen_applications.yml'              
            }
        }
    }
}