pipeline { 
    agent any 
    stages {
        stage('Cloning our Git') { 
            steps { 
                checkout scm
            }
        }
        stage('Building our image') { 
            steps { 
                ansiblePlaybook credentialsId: 'myserver', inventory: 'hosts', playbook: 'ansible_script.yml'                    
                  }
               }
            }
        }
