#IMAGE_NAME = "ubuntu/xenial64" 
#NODE_NAME = "ubuntu"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    #hostname виртуальной машины
    config.vm.hostname = "ubuntu-2004"

    config.vm.provider "virtualbox" do |v|
        v.memory = 4048
        v.cpus = 2
    end
    
    config.ssh.insert_key = true
    config.ssh.forward_agent = true

    #настройка сети (сетевой мост на втором интерфейсе)
    config.vm.network "public_network", ip: "192.168.30.120", bridge: "en0: Wi-Fi (Wireless)"
    
    config.vm.provision "shell", inline: "echo Hello from Shell"

    config.vm.provision "ansible_local" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "deploymen_applications.yml"
    end
end